# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/plugin/plugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pkg/plugin/plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17pkg/plugin/plugin.proto\x12\x06plugin\"H\n\x0e\x45xecuteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\targs_json\x18\x02 \x01(\x0c\x12\x15\n\rscript_source\x18\x03 \x01(\t\"D\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tdata_json\x18\x02 \x01(\x0c\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"\x17\n\x04Pong\x12\x0f\n\x07version\x18\x01 \x01(\t2p\n\rPluginRuntime\x12:\n\x07\x45xecute\x12\x16.plugin.ExecuteRequest\x1a\x17.plugin.ExecuteResponse\x12#\n\x04Ping\x12\r.plugin.Empty\x1a\x0c.plugin.PongB.Z,github.com/diameter-tscd/stackyrd/pkg/pluginb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.plugin.plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/diameter-tscd/stackyrd/pkg/plugin'
  _globals['_EXECUTEREQUEST']._serialized_start=35
  _globals['_EXECUTEREQUEST']._serialized_end=107
  _globals['_EXECUTERESPONSE']._serialized_start=109
  _globals['_EXECUTERESPONSE']._serialized_end=177
  _globals['_EMPTY']._serialized_start=179
  _globals['_EMPTY']._serialized_end=186
  _globals['_PONG']._serialized_start=188
  _globals['_PONG']._serialized_end=211
  _globals['_PLUGINRUNTIME']._serialized_start=213
  _globals['_PLUGINRUNTIME']._serialized_end=325
# @@protoc_insertion_point(module_scope)
