// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pkg/plugin/plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginRuntime_Execute_FullMethodName = "/plugin.PluginRuntime/Execute"
	PluginRuntime_Ping_FullMethodName    = "/plugin.PluginRuntime/Ping"
)

// PluginRuntimeClient is the client API for PluginRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginRuntimeClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
}

type pluginRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginRuntimeClient(cc grpc.ClientConnInterface) PluginRuntimeClient {
	return &pluginRuntimeClient{cc}
}

func (c *pluginRuntimeClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, PluginRuntime_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, PluginRuntime_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginRuntimeServer is the server API for PluginRuntime service.
// All implementations must embed UnimplementedPluginRuntimeServer
// for forward compatibility.
type PluginRuntimeServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	Ping(context.Context, *Empty) (*Pong, error)
	mustEmbedUnimplementedPluginRuntimeServer()
}

// UnimplementedPluginRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginRuntimeServer struct{}

func (UnimplementedPluginRuntimeServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedPluginRuntimeServer) Ping(context.Context, *Empty) (*Pong, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPluginRuntimeServer) mustEmbedUnimplementedPluginRuntimeServer() {}
func (UnimplementedPluginRuntimeServer) testEmbeddedByValue()                       {}

// UnsafePluginRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginRuntimeServer will
// result in compilation errors.
type UnsafePluginRuntimeServer interface {
	mustEmbedUnimplementedPluginRuntimeServer()
}

func RegisterPluginRuntimeServer(s grpc.ServiceRegistrar, srv PluginRuntimeServer) {
	// If the following call panics, it indicates UnimplementedPluginRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginRuntime_ServiceDesc, srv)
}

func _PluginRuntime_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginRuntime_ServiceDesc is the grpc.ServiceDesc for PluginRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.PluginRuntime",
	HandlerType: (*PluginRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _PluginRuntime_Execute_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _PluginRuntime_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/plugin.proto",
}
